apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keycloakclientscopes.k8s.kiwigrid.com
spec:
  group: k8s.kiwigrid.com
  version: v1beta2
  scope: Namespaced
  names:
    kind: KeycloakClientScope
    singular: keycloakclientscope
    plural: keycloakclientscopes
    shortNames: [ kccs ]
  additionalPrinterColumns:
  - name: KEYCLOAK
    type: string
    description: The ID for referencing the Keycloak.
    JSONPath: .spec.keycloak
  - name: REALM
    type: string
    description: The realm of the client scope.
    JSONPath: .spec.realm
  - name: CLIENTSCOPENAME
    type: string
    description: The name of the client scope.
    JSONPath: .spec.name
  - name: TIMESTAMP
    type: string
    description: The timestamp of the client scope.
    JSONPath: .status.timestamp
  - name: ERROR
    type: string
    description: The error of the client scope.
    JSONPath: .status.error
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - realm
          - name
          properties:
            keycloak:
              description: 'Name of Keycloak to use, defaults to: keycloak'
              type: string
            realm:
              description: 'Name of realm to create client scope in'
              type: string
            name:
              description: 'Name of client scope to create'
              type: string
            includeInTokenScope:
              type: boolean
            displayOnConsentScreen:
              type: boolean
            consentScreenText:
              type: string
            guiOrder:
              type: integer
            mappers:
              description: 'Protocol mappers to use'
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  protocolMapper:
                    type: string
                  config:
                    type: object
                    additionalProperties:
                      type: string
        status:
          type: object
          required:
          - timestamp
          properties:
            timestamp:
              type: string
            error:
              type: string